name: Build and Run on Ubuntu

on:
  push:
  pull_request:

jobs:
  build-run-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure with CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Run executable
        run: ./build/main
